name: eslint
on:
  - push
jobs: 
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@master
  - uses: actions/setup-node@v1
    with:
      node-version: '10.x'
  -run: npx install install-peerdeps --dev eslint-config-airbnb-base@latest
  -run: npx eslint .
© 
\
